### PR TITLE
Disable preloader in testing environment 

### LINKED ISSUE #6: disable during testing
Likely unnecessary for testing. Also, preloader may interfere with testem.

### PR DESCRIPTION
**Pull request by simonihmig**
Fixes #6

### CODE REVIEW

**Comment by joebartels** [comment]
awesome @simonihmig ! so looks like this has a side effect of making it impossible to run its own tests :laughing:.
I think we could simply add an extra check that gives us the behavior we need for running tests
e.g. something like
```
if (config.environment === 'test' && !this.addonOptions.enableForTesting) {
  return;
}
```
and just update the ember-cli-app.js accordingly

**Comment by simonihmig** [comment]
Oups! :) Initially I just hacked index.js in my local node_modules to get it running. Had a look there if there were tests I would have to watch for, but did't take into account that tests are excluded from npm modules... Sorry about the confusion. Was in a hurry and/or too late in the evening... 

This PR obviously does not make any sense in this state, will try to update it as suggested. Might be next week, however...

**Comment by joebartels** [comment]
@simonihmig let me know if you want update your branch to get tests running.

If I don't hear from ya by this weekend I'll probably take over the work

**Comment by simonihmig** [comment]
Sorry, I lost track on this one somehow... will try to fix this over the weekend, hope to find the time!

**Comment by joebartels** [comment]
cool. sounds good!

**Comment by joebartels** [comment]
fixed here: https://github.com/Vestorly/ember-cli-preloader/pull/16

**Pull request closed without merging**
